spring.application.name=ventas

#  --- Conexion MySQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/jima?useSSL=false&serverTimezone=America/Mexico_City
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# --- Driver de MySQL ---
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.database-platform=org.hibernate.jdbc.dialect.MySQLDialect

# Servidor
server.port=8080

# Configurar el patron de Logging
logging.level.root=INFO
logging.pattern.console=[%thread] %-5level: %logger - %msg%n

# --- Desactivar banner de spring ---
spring.main.banner-mode=off

# JWT - cambiar el secret en produccion por uno de minimo 32 caracteres
jwt.secret=${SECRET_KEY}
jwt.expiration=28800000
# 28800000 ms = 8 horas

logging.level.org.springframework.security=DEBUG
logging.level.isa.jima.ventas.security=DEBUG
